export const FETCH_MYLIST_DEFAULT_ITEMS_START =
  "FETCH_MYLIST_DEFAULT_ITEMS_START";
export const FETCH_MYLIST_DEFAULT_ITEMS_SUCCESS =
  "FETCH_MYLIST_DEFAULT_ITEMS_FAIL";
export const FETCH_MYLIST_DEFAULT_ITEMS_FAIL =
  "FETCH_MYLIST_DEFAULT_ITEMS_FAIL";

export const ADD_SUPERHERO_TO_MYLIST = "ADD_SUPERHERO_TO_MYLIST";
export const ADD_SUPERHERO_TO_FAVLIST = "ADD_SUPERHERO_TO_FAVLIST";

export const REMOVE_SUPERHERO_FROM_MYLIST_SUCCESS = "REMOVE_SUPERHERO_FROM_MYLIST";
export const REMOVE_SUPERHERO_FROM_FAVLIST = "REMOVE_SUPERHERO_FROM_FAVLIST";